[package]
name = "nbody"
version = "0.1.0"
authors = ["Stefan Lankes <slankes@eonerc.rwth-aachen.de>"]
edition = "2018"
build = "build.rs"

[dependencies]
rayon = "1.0"
packed_simd = "0.3"

[build-dependencies]
cc = "1.0"
